# Generated by Django 5.1.3 on 2024-11-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("products", models.JSONField(null=True)),
                ("totalPrice", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
