# Generated by Django 5.1.3 on 2024-11-30 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="products",
            new_name="orderDetail",
        ),
    ]
