# Generated by Django 4.2.16 on 2024-12-08 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_products_order_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
